### PR TITLE
Implements admin/avatar/maps/profile/session/shards/registration apis and small fixes

### LINKED ISSUE #103: Some apis are not implemented
### Context and Problem Statement

some apis are not implemented, like list maps, so uro can't find an api route when vsekai game sends query 
shards list ("Browse Servers") seems to work 

also there's some api mismatch in game/server /session//login

so it's not ready to replace current stack

avatar list and map list apis for sure

so you get a uro router error when you try to pick a map 

### Describe the proposed option and how it helps to overcome the problem or limitation

Fix it so we can host a server.

### PR DESCRIPTION
**Pull request by dragonhunt02**
#103
### Additions
- Add temporary Mailer config (in-memory email storage) for production. This must be replaced with an email service adapter in final server.
- Serve user content at `/uploads` with Waffle and Caddyfile
- Require `authenticated_user` to access certain endpoints. Since game client and website share some endpoints, a `ChooseAuth` plug was added to fallback to `Cookie` authentication if `Authorization` header is missing.
- Add avatar/maps `/dashboard` endpoints
- Add `/admin` api endpoint and control panel page stub
- Add `/profile` `/session` `/registration` game client endpoints
- Add `/session/renew` dummy endpoint to refresh access tokens for game client compatibility
- Completed `/shards` endpoints implementation
- Add `SIGNUP_API_KEY` key to authenticate game client signup requests
- Add script `priv/repo/test_user_content.exs` to populate database with test user content

### Fixes
- Disable `cache_static_manifest` (no file is served from `priv/static`)
- Fix missing alias in `lib/uro/controllers/identity_proof_controller.ex`
- Add missing function `is_session_admin?/1`
- Fix `Uro.Plug.Authentication` authentication. Client `Authorization` token was not recognized because it was sent without `Bearer ` prefix
- Fix `priv/repo/test_seeds.exs` not confirming email of generated users

Endpoints were tested with `curl`, further testing is needed

**Missing features:**
- Define openapi avatar/maps query specs

### CODE REVIEW

**Comment by dragonhunt02** [comment]
Updated with new endpoints

**Comment by dragonhunt02** [comment]
Updated with `/shards` fixes.

Server can receive uploads and host shards now

File: config/config.exs [hunk 1]
```diff
@@ -155,6 +155,11 @@ config :logger, :console,
 
 config :phoenix, :json_library, Jason
 
+config :waffle,
+  storage: Waffle.Storage.Local
+
+# storage_dir: "uploads"
```
Comment (fire) [inline config/config.exs:161]: Why is this commented?

File: config/prod.exs [hunk 2]
```diff
@@ -1,6 +1,10 @@
 import Config
 
-config :uro, Uro.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
+# Unused (no static files)
```
Comment (fire) [inline config/prod.exs:3]: Typically isn’t there at least a favicon static image?

Comment (dragonhunt02) [reply config/prod.exs:3]: I think we keep them in frontend, see https://github.com/V-Sekai/uro/tree/master/frontend/src/assets

File: config/config.exs (hunk 1 above)
Comment (dragonhunt02) [reply config/config.exs:161]: `/uploads` folder is default when using Waffle, I left this line to make it obvious

**Comment by fire** [comment]
image

Weird

**Comment by dragonhunt02** [comment]
> 
> Weird

All test files are empty dummy files generated with `touch`. I'm not sure what we want to use in final server, however they were good enough as placeholders.

We can replace them after we decide what test scenes to use.

**Review by fire — APPROVED** [review]
Let's merge in a few days.

**Comment by fire** [comment]
My argument for making the test files real is we should not allow fake files in theory. Yes thats hard but we should at least block mime types that don’t match and zero files

**Comment by dragonhunt02** [comment]
> My argument for making the test files real is we should not allow fake files in theory. Yes thats hard but we should at least block mime types that don’t match and zero files

I agree, an extension whitelist is not enough
https://github.com/V-Sekai/uro/blob/9d09c442d4ad85135c4771e236e4d88af4414317/lib/uro/uploaders/user_content_data.ex#L4-L9
I think we should handle this in a new issue though.

By the way, if we make test files real we will have a binary .scn in repository, is it ok? @lyuma

**Comment by lyuma** [comment]
@dragonhunt02 If the binary .scn is for a test scene with a plane and default cube, it should be a few kilobytes which is fine. Same thing for .glb and .vrm

File type Checks could make it harder to add more formats or encrypted formats, so I am worried it will make that more difficult in the future, but for now glb header (.glb and .vrm) and RSRC header (.scn) is all I upload

**Comment by dragonhunt02** [comment]
> @dragonhunt02 If the binary .scn is for a test scene with a plane and default cube, it should be a few kilobytes which is fine. Same thing for .glb and .vrm

.glb and .vrm are blocked right now. Indeed the test scene needs to be a minimal working scene.  :+1: 
 
> File type Checks could make it harder to add more formats or encrypted formats, so I am worried it will make that more difficult in the future, but for now glb header (.glb and .vrm) and RSRC header (.scn) is all I upload

I don't think it will be a problem, we can filter allowed extensions like what we are doing now and then run _optional_ tests to ensure extension matches binaries.

**Comment by lyuma** [comment]
My code in xr_avatar supports glb. This sort of debate is why I'd prefer not to enforce a whitelist for now, but if we do go for a whitelist, I want at least one standardized 3d format such as glb.

**Comment by dragonhunt02** [comment]
> My code in xr_avatar supports glb. This sort of debate is why I'd prefer not to enforce a whitelist for now, but if we do go for a whitelist, I want at least one standardized 3d format such as glb.

Well, whitelist on uploads was already enforced before my PR. So, I will add .glb to allowed extensions (next PR?)

@fire Could you handle generating the test scenes/images?

**Comment by fire** [comment]
1. https://github.com/pixiv/three-vrm/blob/release/packages/three-vrm/examples/models/VRM1_Constraint_Twist_Sample.vrm
2. https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/MetalRoughSpheres/README.md

I can't choose which godot binary scene yet.

**Comment by lyuma** [comment]
I am not okay with anything above a few kilobytes at this stage.
They should be simple, export a cube with no texture for glb. For VRM, we don't technically need a vrm sample since the file format is still glb.

if we really want to write a validator on the server, that should be a separate PR and we need to consider security implications. For now I assume that all this should be doing is checking the magic bytes in the file header

**Comment by fire** [comment]
How about this one? https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SimpleSkin

**Comment by fire** [comment]
We'll need to convert https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/SimpleSkin/glTF-Embedded/SimpleSkin.gltf to glb/scn but it is 3.48 KB.

**Comment by dragonhunt02** [comment]
@fire Lyuma suggested opening another PR for `test_content/` scenes, I agree.
So I removed test_content from this PR.

**Comment by fire** [comment]
Thanks! I am a bit busy this week so I'd like a small tutorial how to run uro.

**Comment by dragonhunt02** [comment]
Instructions are in README.md `Quick Setup`
After booting server with docker compose up, you have to export/run V-Sekai game with https://vsekai.local set as address in `Project Settings/Uro`

I don't have a script ready to quickly install SSL certificates though. Game will fail TLS handshake if they're not correctly installed.

**Comment by fire** [comment]
I can proxy uro through tailscale that has a proper CA and is globally accessible.

**Comment by dragonhunt02** [comment]
Well, you can replace `Caddyfile` with `Caddyfile.development` from my other PR. It run Caddy server on port 80 so you won't have to deal with certificates.

You can send me a message if you find issues setting it up.
